# Default Ktor plugin port
ports:
- port: 8080
  visibility: public

tasks:
  - before: sdk env install && echo "sdkman_auto_env=true" >> ~/.sdkman/etc/config  # install needed toolchain and enable it
    init: ./gradlew classes testClasses # populate build and dependency cache
  - command: docker-compose -f dev.docker-compose.yaml up -d # start dev environment

jetbrains:
  intellij:
    # enable pre-indexing
    prebuilds:
      version: stable
    # Plugins recommended for use with the project
    plugins:
      - me.schlaubi.gradleupdater
      - com.intellij.grazie.pro
