###

POST https://music.youtube.com/youtubei/v1/next
Content-Type: application/json
Referer: https://music.youtube.com/

{
    "videoId": "GfCy_1xKFdU",
    "playlistId": "RDAMVMGfCy_1xKFdU",
    "params": "8gEAmgMDCNgE",
    "context": {
        "client": {
            "clientName": "WEB_REMIX",
            "clientVersion": "1.20220725.01.00"
        }
    }
}

###

POST https://music.youtube.com/youtubei/v1/music/get_search_suggestions
Content-Type: application/json
Referer: https://music.youtube.com/

{
    "input": "Never Gonna Give You Up",
    "context": {
        "client": {
            "clientName": "WEB_REMIX",
            "clientVersion": "1.20220502.01.00"
        }
    }
}
