###

POST https://music.youtube.com/youtubei/v1/next
Content-Type: application/json
Referer: https://music.youtube.com/

{
    "videoId": "GfCy_1xKFdU",
    "playlistId": "RDAMVMGfCy_1xKFdU",
    "params": "8gEAmgMDCNgE",
    "context": {
        "client": {
            "clientName": "WEB_REMIX",
            "clientVersion": "1.20220725.01.00"
        }
    }
}

###

POST https://music.youtube.com/youtubei/v1/music/get_search_suggestions
Content-Type: application/json
Referer: https://music.youtube.com/

{
    "input": "Never Gonna Give You Up",
    "context": {
        "client": {
            "clientName": "WEB_REMIX",
            "clientVersion": "1.20220502.01.00"
        }
    }
}

###

POST https://music.youtube.com/youtubei/v1/next?key=AIzaSyC9XL3ZjWddXya6X74dJoCTL-WEYFDNX30&prettyPrint=false
origin: https://music.youtube.com
Content-Type: application/json

{
    "videoId": "Yx6GdcG5XdM",
    "playlistId": "RDAMVMYx6GdcG5XdM",
    "params": "8gEAmgMDCNgE",
    "context": {
        "client": {
            "hl": "de",
            "gl": "DE",
            "clientName": "WEB_REMIX",
            "clientVersion": "1.20230102.01.00"
        }
    }
}

###


