### Requests Guilds
GET http://localhost:8080/servers
Authorization: Bearer {{token}}

### Requests Guild
GET http://localhost:8080/servers/809471441719787602
Authorization: Bearer {{token}}

### Request poll
GET http://localhost:8080/polls/63e7909335a71a729af42a3a
Authorization: Bearer {{token}}
