package dev.schlaubi.mikbot.gradle;

import dev.schlaubi.mikbot.gradle.extension.ExtensionsKt;
import dev.schlaubi.mikbot.gradle.extension.PluginExtension;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.Properties;

public abstract class PatchPropertiesTask extends DefaultTask {

    @InputDirectory
    public abstract DirectoryProperty getPropertiesDirectory();


    private final PluginExtension extension = getProject().getExtensions().getByType(PluginExtension.class);
    private final String dependenciesString = UtilKt.buildDependenciesString(getProject());
    private final String version = getProject().getVersion().toString();

    @Input
    public PluginExtension getExtension() {
        return extension;
    }

    @TaskAction
    public void runTask() throws IOException {
        if (!getDidWork()) return;
        var properties = new Properties();

        var file = getPropertiesDirectory().get().file("plugin.properties").getAsFile().toPath();
        if (!Files.exists(file)) {
            throw new IllegalStateException("File %s doesn't exist".formatted(file));
        }
        properties.load(Files.newBufferedReader(file));
        properties.setProperty("plugin.id", extension.getPluginId().get());
        properties.setProperty("plugin.version", String.valueOf(version).replace("-SNAPSHOT", ""));
        var requires = extension.getRequires().getOrNull();
        if (requires != null) {
            properties.setProperty("plugin.requires", requires);
        }

        if (!dependenciesString.isBlank()) {
            properties.setProperty("plugin.dependencies", dependenciesString);
        }

        properties.setProperty("plugin.description",
            extension.getDescription().getOrElse("<no description>"));
        properties.setProperty("plugin.provider",
            extension.getProvider().get());
        properties.setProperty("plugin.license",
            extension.getLicense().get());

        try (var writer = Files.newBufferedWriter(file, StandardOpenOption.WRITE)) {
            properties.store(writer, "Generated by Mikbot processor");
        }
    }
}
